package com.hibernate;
// Generated Oct 3, 2016 1:10:48 PM by Hibernate Tools 4.3.1



/**
 * FlatImage generated by hbm2java
 */
public class FlatImage  implements java.io.Serializable {


     private Integer imageId;
     private FlatDescription flatDescription;
     private String image;

    public FlatImage() {
    }

    public FlatImage(FlatDescription flatDescription, String image) {
       this.flatDescription = flatDescription;
       this.image = image;
    }
   
    public Integer getImageId() {
        return this.imageId;
    }
    
    public void setImageId(Integer imageId) {
        this.imageId = imageId;
    }
    public FlatDescription getFlatDescription() {
        return this.flatDescription;
    }
    
    public void setFlatDescription(FlatDescription flatDescription) {
        this.flatDescription = flatDescription;
    }
    public String getImage() {
        return this.image;
    }
    
    public void setImage(String image) {
        this.image = image;
    }




}


