package com.hibernate;
// Generated Oct 3, 2016 1:10:48 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * FlatDescription generated by hbm2java
 */
public class FlatDescription  implements java.io.Serializable {


     private Integer flatDescriptionId;
     private Double flatSize;
     private Integer totalRoom;
     private Integer bedRoom;
     private Integer corridor;
     private Integer washroom;
     private Integer attachedWashroom;
     private String parking;
     private String facing;
     private Integer unit;
     private Double landArea;
     private String flatStatus;
     private Set flatInformations = new HashSet(0);
     private Set flatImages = new HashSet(0);

    public FlatDescription() {
    }

    public FlatDescription(Double flatSize, Integer totalRoom, Integer bedRoom, Integer corridor, Integer washroom, Integer attachedWashroom, String parking, String facing, Integer unit, Double landArea, String flatStatus, Set flatInformations, Set flatImages) {
       this.flatSize = flatSize;
       this.totalRoom = totalRoom;
       this.bedRoom = bedRoom;
       this.corridor = corridor;
       this.washroom = washroom;
       this.attachedWashroom = attachedWashroom;
       this.parking = parking;
       this.facing = facing;
       this.unit = unit;
       this.landArea = landArea;
       this.flatStatus = flatStatus;
       this.flatInformations = flatInformations;
       this.flatImages = flatImages;
    }
   
    public Integer getFlatDescriptionId() {
        return this.flatDescriptionId;
    }
    
    public void setFlatDescriptionId(Integer flatDescriptionId) {
        this.flatDescriptionId = flatDescriptionId;
    }
    public Double getFlatSize() {
        return this.flatSize;
    }
    
    public void setFlatSize(Double flatSize) {
        this.flatSize = flatSize;
    }
    public Integer getTotalRoom() {
        return this.totalRoom;
    }
    
    public void setTotalRoom(Integer totalRoom) {
        this.totalRoom = totalRoom;
    }
    public Integer getBedRoom() {
        return this.bedRoom;
    }
    
    public void setBedRoom(Integer bedRoom) {
        this.bedRoom = bedRoom;
    }
    public Integer getCorridor() {
        return this.corridor;
    }
    
    public void setCorridor(Integer corridor) {
        this.corridor = corridor;
    }
    public Integer getWashroom() {
        return this.washroom;
    }
    
    public void setWashroom(Integer washroom) {
        this.washroom = washroom;
    }
    public Integer getAttachedWashroom() {
        return this.attachedWashroom;
    }
    
    public void setAttachedWashroom(Integer attachedWashroom) {
        this.attachedWashroom = attachedWashroom;
    }
    public String getParking() {
        return this.parking;
    }
    
    public void setParking(String parking) {
        this.parking = parking;
    }
    public String getFacing() {
        return this.facing;
    }
    
    public void setFacing(String facing) {
        this.facing = facing;
    }
    public Integer getUnit() {
        return this.unit;
    }
    
    public void setUnit(Integer unit) {
        this.unit = unit;
    }
    public Double getLandArea() {
        return this.landArea;
    }
    
    public void setLandArea(Double landArea) {
        this.landArea = landArea;
    }
    public String getFlatStatus() {
        return this.flatStatus;
    }
    
    public void setFlatStatus(String flatStatus) {
        this.flatStatus = flatStatus;
    }
    public Set getFlatInformations() {
        return this.flatInformations;
    }
    
    public void setFlatInformations(Set flatInformations) {
        this.flatInformations = flatInformations;
    }
    public Set getFlatImages() {
        return this.flatImages;
    }
    
    public void setFlatImages(Set flatImages) {
        this.flatImages = flatImages;
    }




}


