package com.hibernate;
// Generated Oct 3, 2016 1:10:48 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * FlatAddress generated by hbm2java
 */
public class FlatAddress  implements java.io.Serializable {


     private Integer addressId;
     private String flatNo;
     private String houseNo;
     private String roadNo;
     private String moholla;
     private String thana;
     private String district;
     private Set flatInformations = new HashSet(0);

    public FlatAddress() {
    }

    public FlatAddress(String flatNo, String houseNo, String roadNo, String moholla, String thana, String district, Set flatInformations) {
       this.flatNo = flatNo;
       this.houseNo = houseNo;
       this.roadNo = roadNo;
       this.moholla = moholla;
       this.thana = thana;
       this.district = district;
       this.flatInformations = flatInformations;
    }
   
    public Integer getAddressId() {
        return this.addressId;
    }
    
    public void setAddressId(Integer addressId) {
        this.addressId = addressId;
    }
    public String getFlatNo() {
        return this.flatNo;
    }
    
    public void setFlatNo(String flatNo) {
        this.flatNo = flatNo;
    }
    public String getHouseNo() {
        return this.houseNo;
    }
    
    public void setHouseNo(String houseNo) {
        this.houseNo = houseNo;
    }
    public String getRoadNo() {
        return this.roadNo;
    }
    
    public void setRoadNo(String roadNo) {
        this.roadNo = roadNo;
    }
    public String getMoholla() {
        return this.moholla;
    }
    
    public void setMoholla(String moholla) {
        this.moholla = moholla;
    }
    public String getThana() {
        return this.thana;
    }
    
    public void setThana(String thana) {
        this.thana = thana;
    }
    public String getDistrict() {
        return this.district;
    }
    
    public void setDistrict(String district) {
        this.district = district;
    }
    public Set getFlatInformations() {
        return this.flatInformations;
    }
    
    public void setFlatInformations(Set flatInformations) {
        this.flatInformations = flatInformations;
    }




}


