package com.hibernate;
// Generated Oct 3, 2016 1:10:48 PM by Hibernate Tools 4.3.1



/**
 * Location generated by hbm2java
 */
public class Location  implements java.io.Serializable {


     private Integer LId;
     private Integer flatInfoId;
     private Double lat;
     private Double lon;

    public Location() {
    }

    public Location(Integer flatInfoId, Double lat, Double lon) {
       this.flatInfoId = flatInfoId;
       this.lat = lat;
       this.lon = lon;
    }
   
    public Integer getLId() {
        return this.LId;
    }
    
    public void setLId(Integer LId) {
        this.LId = LId;
    }
    public Integer getFlatInfoId() {
        return this.flatInfoId;
    }
    
    public void setFlatInfoId(Integer flatInfoId) {
        this.flatInfoId = flatInfoId;
    }
    public Double getLat() {
        return this.lat;
    }
    
    public void setLat(Double lat) {
        this.lat = lat;
    }
    public Double getLon() {
        return this.lon;
    }
    
    public void setLon(Double lon) {
        this.lon = lon;
    }




}


